services:
  jupyter:
    container_name: jupyter
    hostname: jupyter
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    environment:
      - http_proxy=$http_proxy
      - https_proxy=$https_proxy
      - no_proxy=$no_proxy
    volumes:
      - /home/jesper/projects/jet_engine_rul:/home/jovyan/work/jet_engine_rul
